# Generated by Django 3.2 on 2021-04-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.IntegerField()),
                ('id_instructor', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
                ('lieu', models.CharField(max_length=100)),
            ],
        ),
    ]
