# Generated by Django 3.2 on 2021-04-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planning',
            name='heure',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
